version: '3'
services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/code
      - ivy2:/root/.ivy2
      - cache:/root/.cache
      - sbt:/root/.sbt
      - sbtlib:/usr/share/sbt/lib

volumes:
  ivy2: {}
  cache: {}
  sbt: {}
  sbtlib: {}
